### ISSUE TITLE
oninput event doesn't trigger

### ISSUE THREAD

**Issue by henryxrl** [yairEO/color-picker#1]
Hello,
It seems like the `oninput` event can never get triggered while the default color picker can.
I also tried to remove `inputmode="none"` attribute but `oninput` event is still not triggered. 
Any solutions/workarounds? Thanks for your time!

**Comment by yairEO** [comment]
Why don't/can't you use the `onInput` setting just like it is shown in the [example](https://github.com/yairEO/color-picker#example)

```js
const cPicker = new ColorPicker({
  ...
  
  // fired rapidly, on every range slider movement or any color change
  onInput(color){},

  // like "onInput", but not fired while a range slider is moved
  onChange(color){},
})
```

**Comment by henryxrl** [comment]
Yup. At the end I modified the `onInput` function. Thanks!
