### ISSUE TITLE
Nothing exported on 0.12.x

### ISSUE THREAD

**Issue by sapandiwakar** [yairEO/color-picker#2]
It seems that version 0.12.x doesn't export anything. 

```js
import ColorPicker from '@yaireo/color-picker';
```
raises `Attempted import error: '@yaireo/color-picker' does not contain a default export`. 

```js
import * as ColorPicker from '@yaireo/color-picker';
```
does not raise any errors but ColorPicker is just an empty object `{}` and does not contain any exports. 

`0.11.0` works fine. 

For the record, the build system in use was `esbuild` and I have tried both with node `18.15.0` and `20.5.0` (I understand that 20 is incompatible with the engines defined in `package.json`).

**Comment by yairEO** [comment]
I will take a look

**Comment by yairEO** [comment]
Fixed https://github.com/yairEO/color-picker/releases/tag/v0.13.0
